### ISSUE TITLE
Array fields not properly carried over to partial types

### ISSUE THREAD

**Issue by caldarellial** [uniquenode/type-graphql-utils#3]
Hello!

I've been making use of the Partial() helper a lot in my project and have noticed that it fails to carry over the "array" typeOption. It seems this occurs because array and arrayDepth don't get assigned until getType is called for the first time.
https://github.com/MichalLytek/type-graphql/blob/3733b1e57cb7ea8432420a17b3660c69187e0a09/src/helpers/findType.ts#L60

If I edit the source of type-graphql-utils to call getType on the field, it works.

```typescript
metadata.fields.forEach((f) => {
        if (f.target !== BaseClass && !f.target.isPrototypeOf(BaseClass))
            return;
        f.getType(); // added this
        const field = buildFn(f);
        if (field instanceof Array) {
            field.forEach((field) => metadata.fields.push({ ...field, target: ChildClass }));
        }
        else if (field) {
            metadata.fields.push({ ...field, target: ChildClass });
        }
    });
```

Current state, without getType()
![image](https://user-images.githubusercontent.com/7096661/199064594-c005a1b2-6346-48fd-a505-fe61635828a0.png)

with getType()
![image](https://user-images.githubusercontent.com/7096661/199064948-c54f46de-4ed5-455c-b3bf-f374eebfcfd2.png)

**Comment by uniquenode** [comment]
Hey @caldarellial!

Thank you for reporting this issue, and great to hear you are using this library.
Sorry for taking so long, for some reason I didn't get notified of this issue.

I have just released version `2.0.0` which includes your fix.

Thank you!
